options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/turnkey-cove-460604-p4/fastapi-app:latest','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/turnkey-cove-460604-p4/fastapi-app:latest']

images:
  - 'gcr.io/turnkey-cove-460604-p4/fastapi-app:latest'