# options:
#   logging: CLOUD_LOGGING_ONLY
options:
  logging: CLOUD_LOGGING_ONLY
  
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/test-rag-461501/fastapi-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/test-rag-461501/fastapi-app:latest']

images:
  - 'gcr.io/test-rag-461501/fastapi-app:latest'